import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BRW",
  description: "Generated by create next app",
};
import { PackageProvider } from "../context/page";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <title>{metadata.title}</title>
        </header>

        <Header />
        <PackageProvider>

          {children}
        </PackageProvider>
      </body>
    </html>
  );
}
{
}
